import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import { Providers } from '@/app/providers';
import TableSkeletonProvider from '@/ui/skeletons/table-skeleton-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Salbutes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen bg-slate-300 px-5 py-5 antialiased md:px-20 md:py-20`}
      >
        <TableSkeletonProvider>
          <Providers>{children}</Providers>
        </TableSkeletonProvider>
      </body>
    </html>
  );
}
